server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: qualquer rota que não seja arquivo ou API vai pro index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para a API via ALB (mesmo ALB, porta 8081)
    location /tasks {
        proxy_pass http://alb-obs-app-1648701542.us-east-1.elb.amazonaws.com:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://alb-obs-app-1648701542.us-east-1.elb.amazonaws.com:8081;
        proxy_set_header Host $host;
    }
}
