server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: qualquer rota que não seja arquivo vai pro index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para a API (em produção, trocar pelo endereço do service discovery ou ALB)
    location /tasks {
        proxy_pass http://kanban-api:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://kanban-api:3001;
        proxy_set_header Host $host;
    }
}
